name: demo
on: workflow_dispatch # helps to trigger manually on github actions page
jobs:
  sampleapp-build:
    runs-on: ubuntu-latest
    steps: 
     - name: get code
       uses: actions/checkout@v4
     # - name: compile
     #   run: mvn compile
     # - name: review
     #   run: mvn -P metrics pmd:pmd
     # - name: test
     #   run: mvn test
     # - name: verify
     #   run: mvn verify
     - name: deploy
       run: |
        mkdir ~/.m2
        echo "<settings><servers><server><id>github</id><username>OWNER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn deploy
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
